apiVersion: v1
kind: Namespace
metadata:
  name: nsp-uat
  labels:
    env: uat
---
apiVersion: v1
kind: Namespace
metadata:
  name: nsp-stg
  labels:
    env: stg
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-uat
  namespace: nsp-uat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-uat
  template:
    metadata:
      labels:
        app: backend-uat
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-stg
  namespace: nsp-stg
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-stg
  template:
    metadata:
      labels:
        app: backend-stg
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
