apiVersion: v1
kind: Pod
metadata:
  name: server3
spec:
  containers:
    - name: contenedor1
      image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: server4
spec:
  containers:
    - name: contenedor1
      image: nginx:alpine
