apiVersion: v1
kind: Pod
metadata:
  name: server3
  labels:
    env: dev
    app: frontend
spec:
  containers:
    - name: contenedor1
      image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: server4
  labels:
    env: dev
    app: backend
spec:
  containers:
    - name: contenedor1
      image: jenkins/jenkins
