apiVersion: v1
kind: Pod
metadata:
  name: democpu1
spec:
  containers:
    - name: democpu1
      image: vish/stress
      resources:
        limits:
          cpu: "1"
        requests:
          cpu: "0.5"
