apiVersion: v1
kind: Pod
metadata:
  name: memory-ram
spec:
  containers:
    - name: memoryram
      image: polinux/stress
      resources:
        limits:
          memory: "200Mi"
        requests:
          memory: "100Mi"
      args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
      command: ["stress"]
