apiVersion: v1
kind: Secret
metadata:
  name: supersecreto
type: Opaque
data:
  user: dXN1YXJpb0FkbWlu
  pass: MTIzNDU=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: desploy-cm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: supersecreto
                  key: user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: supersecreto
                  key: pass
