version: "3.8"

services:
  server:
    #image: nginx:stable-alpine
    container_name: server
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - "9010:80"
    depends_on:
      - php
      - mysql
    #volumes:
    #  - ./src:/var/www/html
    #  - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    container_name: php
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    #volumes:
    #  - ./src:/var/www/html:delegated

  mysql:
    container_name: mysql
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
  # UTILITARIOS

  composer:
    container_name: composer
    build:
      context: .
      dockerfile: dockerfiles/composer.dockerfile
    volumes:
      - ./src:/var/www/html
